name: webleger_task
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #. media icons
  shimmer: ^3.0.0
  icons_plus: ^5.0.0

  #. internationalization

  #. state management
  get: ^4.7.2
  get_storage: ^2.1.1

  #. network
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.3
  json_annotation: ^4.9.0

  #. utils
  cached_network_image: ^3.4.1
  logger: ^2.5.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
